/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AgriDetails {
  'subType' : AgriSubType,
  'subsidyFields' : [] | [SubsidyFields],
  'saleFields' : [] | [SaleFields],
}
export type AgriSubType = { 'Sale' : null } |
  { 'Subsidy' : null };
export interface Branch { 'id' : bigint, 'name' : string, 'isActive' : boolean }
export type CallDetails = { 'Agri' : AgriDetails } |
  { 'CivilEquip' : SaleFields } |
  { 'IndustrialEquip' : SaleFields };
export interface CallLog {
  'id' : bigint,
  'duration' : [] | [bigint],
  'callStatus' : CallStatus,
  'createdAt' : Timestamp,
  'callerId' : UserId,
  'leadId' : bigint,
  'notes' : [] | [string],
  'callTimestamp' : Timestamp,
  'details' : [] | [CallDetails],
  'outcome' : [] | [CallOutcome],
}
export type CallOutcome = { 'NotReachable' : null } |
  { 'SwitchOff' : null } |
  { 'Interested' : null } |
  { 'NotInterested' : null };
export interface CallReport {
  'switchOffCount' : bigint,
  'totalDurationSecs' : bigint,
  'totalCalls' : bigint,
  'interestedCount' : bigint,
  'notReachableCount' : bigint,
  'notConnectedCalls' : bigint,
  'connectedCalls' : bigint,
  'notInterestedCount' : bigint,
}
export interface CallReportFilter {
  'userId' : [] | [UserId],
  'dateRange' : [] | [DateRange],
}
export type CallStatus = { 'Connected' : null } |
  { 'NotConnected' : null };
export interface Campaign {
  'id' : bigint,
  'endDate' : [] | [string],
  'source' : [] | [string],
  'name' : string,
  'isActive' : boolean,
  'budget' : [] | [bigint],
  'startDate' : [] | [string],
}
export interface CreateFollowUpInput {
  'scheduledDate' : string,
  'scheduledTime' : string,
  'reminderEnabled' : boolean,
  'leadId' : bigint,
  'notes' : [] | [string],
}
export interface CreateLeadInput {
  'status' : LeadStatus,
  'source' : [] | [string],
  'campaign' : [] | [string],
  'name' : string,
  'email' : [] | [string],
  'notes' : [] | [string],
  'productInterest' : [] | [string],
  'priority' : Priority,
  'phone' : string,
  'assignedUserId' : [] | [UserId],
  'altPhone' : [] | [string],
}
export interface DateRange { 'toTs' : Timestamp, 'fromTs' : Timestamp }
export type DocStatus = { 'Collected' : null } |
  { 'Pending' : null };
export interface FollowUp {
  'id' : bigint,
  'isCompleted' : boolean,
  'scheduledDate' : string,
  'scheduledTime' : string,
  'createdAt' : Timestamp,
  'reminderEnabled' : boolean,
  'leadId' : bigint,
  'notes' : [] | [string],
  'completionNotes' : [] | [string],
}
export type FollowUpFilter = { 'Missed' : null } |
  { 'Today' : null } |
  { 'Completed' : null } |
  { 'Upcoming' : null };
export interface Lead {
  'id' : bigint,
  'status' : LeadStatus,
  'source' : [] | [string],
  'campaign' : [] | [string],
  'name' : string,
  'createdAt' : Timestamp,
  'email' : [] | [string],
  'updatedAt' : Timestamp,
  'notes' : [] | [string],
  'productInterest' : [] | [string],
  'priority' : Priority,
  'phone' : string,
  'assignedUserId' : [] | [UserId],
  'altPhone' : [] | [string],
}
export interface LeadFilter {
  'status' : [] | [LeadStatus],
  'source' : [] | [string],
  'campaign' : [] | [string],
  'searchText' : [] | [string],
  'priority' : [] | [Priority],
  'assignedUserId' : [] | [UserId],
}
export interface LeadReport {
  'closedWon' : bigint,
  'totalLeads' : bigint,
  'proposalSent' : bigint,
  'newLeads' : bigint,
  'conversionPercent' : bigint,
  'qualified' : bigint,
  'closedLost' : bigint,
}
export interface LeadReportFilter {
  'source' : [] | [string],
  'campaign' : [] | [string],
  'userId' : [] | [UserId],
  'dateRange' : [] | [DateRange],
}
export type LeadStatus = { 'New' : null } |
  { 'Proposal' : null } |
  { 'ClosedWon' : null } |
  { 'Interested' : null } |
  { 'ClosedLost' : null };
export interface LogCallInput {
  'duration' : [] | [bigint],
  'callStatus' : CallStatus,
  'leadId' : bigint,
  'notes' : [] | [string],
  'callTimestamp' : Timestamp,
  'details' : [] | [CallDetails],
  'outcome' : [] | [CallOutcome],
}
export type Priority = { 'Hot' : null } |
  { 'Cold' : null } |
  { 'Warm' : null };
export interface Product {
  'id' : bigint,
  'categoryId' : bigint,
  'name' : string,
  'isActive' : boolean,
}
export interface ProductCategory {
  'id' : bigint,
  'name' : string,
  'isActive' : boolean,
}
export interface SaleFields {
  'productCategoryId' : bigint,
  'productId' : bigint,
  'priority' : Priority,
  'place' : [] | [string],
  'followUpDate' : [] | [Timestamp],
}
export interface Source { 'id' : bigint, 'name' : string, 'isActive' : boolean }
export interface SubsidyFields {
  'productCategoryId' : bigint,
  'division' : [] | [string],
  'productId' : bigint,
  'district' : string,
  'docStatus' : DocStatus,
  'village' : string,
  'block' : string,
  'farmerName' : string,
}
export type Timestamp = bigint;
export interface UpdateFollowUpInput {
  'id' : bigint,
  'isCompleted' : [] | [boolean],
  'scheduledDate' : [] | [string],
  'scheduledTime' : [] | [string],
  'reminderEnabled' : [] | [boolean],
  'notes' : [] | [string],
  'completionNotes' : [] | [string],
}
export interface UpdateLeadInput {
  'id' : bigint,
  'status' : [] | [LeadStatus],
  'source' : [] | [string],
  'campaign' : [] | [string],
  'name' : [] | [string],
  'email' : [] | [string],
  'notes' : [] | [string],
  'productInterest' : [] | [string],
  'priority' : [] | [Priority],
  'phone' : [] | [string],
  'assignedUserId' : [] | [UserId],
  'altPhone' : [] | [string],
}
export type UserId = Principal;
export interface UserInfo { 'id' : Principal, 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addBranch' : ActorMethod<[string], Branch>,
  'addCampaign' : ActorMethod<[Campaign], Campaign>,
  'addLead' : ActorMethod<[CreateLeadInput], Lead>,
  'addProduct' : ActorMethod<[bigint, string], Product>,
  'addProductCategory' : ActorMethod<[string], ProductCategory>,
  'addSource' : ActorMethod<[string], Source>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignLead' : ActorMethod<[bigint, UserId], boolean>,
  'assignUserRole' : ActorMethod<[Principal, string], undefined>,
  'deleteBranch' : ActorMethod<[bigint], boolean>,
  'deleteCampaign' : ActorMethod<[bigint], boolean>,
  'deleteFollowUp' : ActorMethod<[bigint], boolean>,
  'deleteLead' : ActorMethod<[bigint], boolean>,
  'deleteProduct' : ActorMethod<[bigint], boolean>,
  'deleteProductCategory' : ActorMethod<[bigint], boolean>,
  'deleteSource' : ActorMethod<[bigint], boolean>,
  'getCallReport' : ActorMethod<[CallReportFilter], CallReport>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserInfo]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCallsForLead' : ActorMethod<[bigint], Array<CallLog>>,
  'getFollowUpsForLead' : ActorMethod<[bigint], Array<FollowUp>>,
  'getLeadById' : ActorMethod<[bigint], [] | [Lead]>,
  'getLeadReport' : ActorMethod<[LeadReportFilter], LeadReport>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserInfo]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listBranches' : ActorMethod<[], Array<Branch>>,
  'listCampaigns' : ActorMethod<[], Array<Campaign>>,
  'listLeads' : ActorMethod<[[] | [LeadFilter]], Array<Lead>>,
  'listProductCategories' : ActorMethod<[], Array<ProductCategory>>,
  'listProducts' : ActorMethod<[[] | [bigint]], Array<Product>>,
  'listSources' : ActorMethod<[], Array<Source>>,
  'listUsers' : ActorMethod<[], Array<UserInfo>>,
  'logCall' : ActorMethod<[LogCallInput], CallLog>,
  'logFollowUp' : ActorMethod<[CreateFollowUpInput], FollowUp>,
  'queryFollowUps' : ActorMethod<[FollowUpFilter], Array<FollowUp>>,
  'saveCallerUserProfile' : ActorMethod<[string], undefined>,
  'updateBranch' : ActorMethod<[bigint, string], boolean>,
  'updateCampaign' : ActorMethod<[Campaign], boolean>,
  'updateFollowUpStatus' : ActorMethod<[UpdateFollowUpInput], boolean>,
  'updateLead' : ActorMethod<[UpdateLeadInput], boolean>,
  'updateProduct' : ActorMethod<[bigint, string], boolean>,
  'updateProductCategory' : ActorMethod<[bigint, string], boolean>,
  'updateSource' : ActorMethod<[bigint, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];