/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Branch = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const Campaign = IDL.Record({
  'id' : IDL.Nat,
  'endDate' : IDL.Opt(IDL.Text),
  'source' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'budget' : IDL.Opt(IDL.Nat),
  'startDate' : IDL.Opt(IDL.Text),
});
export const LeadStatus = IDL.Variant({
  'New' : IDL.Null,
  'Proposal' : IDL.Null,
  'ClosedWon' : IDL.Null,
  'Interested' : IDL.Null,
  'ClosedLost' : IDL.Null,
});
export const Priority = IDL.Variant({
  'Hot' : IDL.Null,
  'Cold' : IDL.Null,
  'Warm' : IDL.Null,
});
export const UserId = IDL.Principal;
export const CreateLeadInput = IDL.Record({
  'status' : LeadStatus,
  'source' : IDL.Opt(IDL.Text),
  'campaign' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'notes' : IDL.Opt(IDL.Text),
  'productInterest' : IDL.Opt(IDL.Text),
  'priority' : Priority,
  'phone' : IDL.Text,
  'assignedUserId' : IDL.Opt(UserId),
  'altPhone' : IDL.Opt(IDL.Text),
});
export const Timestamp = IDL.Int;
export const Lead = IDL.Record({
  'id' : IDL.Nat,
  'status' : LeadStatus,
  'source' : IDL.Opt(IDL.Text),
  'campaign' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Opt(IDL.Text),
  'updatedAt' : Timestamp,
  'notes' : IDL.Opt(IDL.Text),
  'productInterest' : IDL.Opt(IDL.Text),
  'priority' : Priority,
  'phone' : IDL.Text,
  'assignedUserId' : IDL.Opt(UserId),
  'altPhone' : IDL.Opt(IDL.Text),
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const ProductCategory = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const Source = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DateRange = IDL.Record({
  'toTs' : Timestamp,
  'fromTs' : Timestamp,
});
export const CallReportFilter = IDL.Record({
  'userId' : IDL.Opt(UserId),
  'dateRange' : IDL.Opt(DateRange),
});
export const CallReport = IDL.Record({
  'switchOffCount' : IDL.Nat,
  'totalDurationSecs' : IDL.Nat,
  'totalCalls' : IDL.Nat,
  'interestedCount' : IDL.Nat,
  'notReachableCount' : IDL.Nat,
  'notConnectedCalls' : IDL.Nat,
  'connectedCalls' : IDL.Nat,
  'notInterestedCount' : IDL.Nat,
});
export const UserInfo = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'role' : IDL.Text,
});
export const CallStatus = IDL.Variant({
  'Connected' : IDL.Null,
  'NotConnected' : IDL.Null,
});
export const AgriSubType = IDL.Variant({
  'Sale' : IDL.Null,
  'Subsidy' : IDL.Null,
});
export const DocStatus = IDL.Variant({
  'Collected' : IDL.Null,
  'Pending' : IDL.Null,
});
export const SubsidyFields = IDL.Record({
  'productCategoryId' : IDL.Nat,
  'division' : IDL.Opt(IDL.Text),
  'productId' : IDL.Nat,
  'district' : IDL.Text,
  'docStatus' : DocStatus,
  'village' : IDL.Text,
  'block' : IDL.Text,
  'farmerName' : IDL.Text,
});
export const SaleFields = IDL.Record({
  'productCategoryId' : IDL.Nat,
  'productId' : IDL.Nat,
  'priority' : Priority,
  'place' : IDL.Opt(IDL.Text),
  'followUpDate' : IDL.Opt(Timestamp),
});
export const AgriDetails = IDL.Record({
  'subType' : AgriSubType,
  'subsidyFields' : IDL.Opt(SubsidyFields),
  'saleFields' : IDL.Opt(SaleFields),
});
export const CallDetails = IDL.Variant({
  'Agri' : AgriDetails,
  'CivilEquip' : SaleFields,
  'IndustrialEquip' : SaleFields,
});
export const CallOutcome = IDL.Variant({
  'NotReachable' : IDL.Null,
  'SwitchOff' : IDL.Null,
  'Interested' : IDL.Null,
  'NotInterested' : IDL.Null,
});
export const CallLog = IDL.Record({
  'id' : IDL.Nat,
  'duration' : IDL.Opt(IDL.Nat),
  'callStatus' : CallStatus,
  'createdAt' : Timestamp,
  'callerId' : UserId,
  'leadId' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
  'callTimestamp' : Timestamp,
  'details' : IDL.Opt(CallDetails),
  'outcome' : IDL.Opt(CallOutcome),
});
export const FollowUp = IDL.Record({
  'id' : IDL.Nat,
  'isCompleted' : IDL.Bool,
  'scheduledDate' : IDL.Text,
  'scheduledTime' : IDL.Text,
  'createdAt' : Timestamp,
  'reminderEnabled' : IDL.Bool,
  'leadId' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
  'completionNotes' : IDL.Opt(IDL.Text),
});
export const LeadReportFilter = IDL.Record({
  'source' : IDL.Opt(IDL.Text),
  'campaign' : IDL.Opt(IDL.Text),
  'userId' : IDL.Opt(UserId),
  'dateRange' : IDL.Opt(DateRange),
});
export const LeadReport = IDL.Record({
  'closedWon' : IDL.Nat,
  'totalLeads' : IDL.Nat,
  'proposalSent' : IDL.Nat,
  'newLeads' : IDL.Nat,
  'conversionPercent' : IDL.Nat,
  'qualified' : IDL.Nat,
  'closedLost' : IDL.Nat,
});
export const LeadFilter = IDL.Record({
  'status' : IDL.Opt(LeadStatus),
  'source' : IDL.Opt(IDL.Text),
  'campaign' : IDL.Opt(IDL.Text),
  'searchText' : IDL.Opt(IDL.Text),
  'priority' : IDL.Opt(Priority),
  'assignedUserId' : IDL.Opt(UserId),
});
export const LogCallInput = IDL.Record({
  'duration' : IDL.Opt(IDL.Nat),
  'callStatus' : CallStatus,
  'leadId' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
  'callTimestamp' : Timestamp,
  'details' : IDL.Opt(CallDetails),
  'outcome' : IDL.Opt(CallOutcome),
});
export const CreateFollowUpInput = IDL.Record({
  'scheduledDate' : IDL.Text,
  'scheduledTime' : IDL.Text,
  'reminderEnabled' : IDL.Bool,
  'leadId' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
});
export const FollowUpFilter = IDL.Variant({
  'Missed' : IDL.Null,
  'Today' : IDL.Null,
  'Completed' : IDL.Null,
  'Upcoming' : IDL.Null,
});
export const UpdateFollowUpInput = IDL.Record({
  'id' : IDL.Nat,
  'isCompleted' : IDL.Opt(IDL.Bool),
  'scheduledDate' : IDL.Opt(IDL.Text),
  'scheduledTime' : IDL.Opt(IDL.Text),
  'reminderEnabled' : IDL.Opt(IDL.Bool),
  'notes' : IDL.Opt(IDL.Text),
  'completionNotes' : IDL.Opt(IDL.Text),
});
export const UpdateLeadInput = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Opt(LeadStatus),
  'source' : IDL.Opt(IDL.Text),
  'campaign' : IDL.Opt(IDL.Text),
  'name' : IDL.Opt(IDL.Text),
  'email' : IDL.Opt(IDL.Text),
  'notes' : IDL.Opt(IDL.Text),
  'productInterest' : IDL.Opt(IDL.Text),
  'priority' : IDL.Opt(Priority),
  'phone' : IDL.Opt(IDL.Text),
  'assignedUserId' : IDL.Opt(UserId),
  'altPhone' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addBranch' : IDL.Func([IDL.Text], [Branch], []),
  'addCampaign' : IDL.Func([Campaign], [Campaign], []),
  'addLead' : IDL.Func([CreateLeadInput], [Lead], []),
  'addProduct' : IDL.Func([IDL.Nat, IDL.Text], [Product], []),
  'addProductCategory' : IDL.Func([IDL.Text], [ProductCategory], []),
  'addSource' : IDL.Func([IDL.Text], [Source], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignLead' : IDL.Func([IDL.Nat, UserId], [IDL.Bool], []),
  'assignUserRole' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'deleteBranch' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteCampaign' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteFollowUp' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteLead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteProductCategory' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteSource' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getCallReport' : IDL.Func([CallReportFilter], [CallReport], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserInfo)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCallsForLead' : IDL.Func([IDL.Nat], [IDL.Vec(CallLog)], ['query']),
  'getFollowUpsForLead' : IDL.Func([IDL.Nat], [IDL.Vec(FollowUp)], ['query']),
  'getLeadById' : IDL.Func([IDL.Nat], [IDL.Opt(Lead)], ['query']),
  'getLeadReport' : IDL.Func([LeadReportFilter], [LeadReport], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserInfo)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listBranches' : IDL.Func([], [IDL.Vec(Branch)], ['query']),
  'listCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
  'listLeads' : IDL.Func([IDL.Opt(LeadFilter)], [IDL.Vec(Lead)], ['query']),
  'listProductCategories' : IDL.Func([], [IDL.Vec(ProductCategory)], ['query']),
  'listProducts' : IDL.Func([IDL.Opt(IDL.Nat)], [IDL.Vec(Product)], ['query']),
  'listSources' : IDL.Func([], [IDL.Vec(Source)], ['query']),
  'listUsers' : IDL.Func([], [IDL.Vec(UserInfo)], ['query']),
  'logCall' : IDL.Func([LogCallInput], [CallLog], []),
  'logFollowUp' : IDL.Func([CreateFollowUpInput], [FollowUp], []),
  'queryFollowUps' : IDL.Func([FollowUpFilter], [IDL.Vec(FollowUp)], ['query']),
  'saveCallerUserProfile' : IDL.Func([IDL.Text], [], []),
  'updateBranch' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'updateCampaign' : IDL.Func([Campaign], [IDL.Bool], []),
  'updateFollowUpStatus' : IDL.Func([UpdateFollowUpInput], [IDL.Bool], []),
  'updateLead' : IDL.Func([UpdateLeadInput], [IDL.Bool], []),
  'updateProduct' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'updateProductCategory' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'updateSource' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Branch = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const Campaign = IDL.Record({
    'id' : IDL.Nat,
    'endDate' : IDL.Opt(IDL.Text),
    'source' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'budget' : IDL.Opt(IDL.Nat),
    'startDate' : IDL.Opt(IDL.Text),
  });
  const LeadStatus = IDL.Variant({
    'New' : IDL.Null,
    'Proposal' : IDL.Null,
    'ClosedWon' : IDL.Null,
    'Interested' : IDL.Null,
    'ClosedLost' : IDL.Null,
  });
  const Priority = IDL.Variant({
    'Hot' : IDL.Null,
    'Cold' : IDL.Null,
    'Warm' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const CreateLeadInput = IDL.Record({
    'status' : LeadStatus,
    'source' : IDL.Opt(IDL.Text),
    'campaign' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'notes' : IDL.Opt(IDL.Text),
    'productInterest' : IDL.Opt(IDL.Text),
    'priority' : Priority,
    'phone' : IDL.Text,
    'assignedUserId' : IDL.Opt(UserId),
    'altPhone' : IDL.Opt(IDL.Text),
  });
  const Timestamp = IDL.Int;
  const Lead = IDL.Record({
    'id' : IDL.Nat,
    'status' : LeadStatus,
    'source' : IDL.Opt(IDL.Text),
    'campaign' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Opt(IDL.Text),
    'updatedAt' : Timestamp,
    'notes' : IDL.Opt(IDL.Text),
    'productInterest' : IDL.Opt(IDL.Text),
    'priority' : Priority,
    'phone' : IDL.Text,
    'assignedUserId' : IDL.Opt(UserId),
    'altPhone' : IDL.Opt(IDL.Text),
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const ProductCategory = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const Source = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DateRange = IDL.Record({ 'toTs' : Timestamp, 'fromTs' : Timestamp });
  const CallReportFilter = IDL.Record({
    'userId' : IDL.Opt(UserId),
    'dateRange' : IDL.Opt(DateRange),
  });
  const CallReport = IDL.Record({
    'switchOffCount' : IDL.Nat,
    'totalDurationSecs' : IDL.Nat,
    'totalCalls' : IDL.Nat,
    'interestedCount' : IDL.Nat,
    'notReachableCount' : IDL.Nat,
    'notConnectedCalls' : IDL.Nat,
    'connectedCalls' : IDL.Nat,
    'notInterestedCount' : IDL.Nat,
  });
  const UserInfo = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'role' : IDL.Text,
  });
  const CallStatus = IDL.Variant({
    'Connected' : IDL.Null,
    'NotConnected' : IDL.Null,
  });
  const AgriSubType = IDL.Variant({ 'Sale' : IDL.Null, 'Subsidy' : IDL.Null });
  const DocStatus = IDL.Variant({
    'Collected' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const SubsidyFields = IDL.Record({
    'productCategoryId' : IDL.Nat,
    'division' : IDL.Opt(IDL.Text),
    'productId' : IDL.Nat,
    'district' : IDL.Text,
    'docStatus' : DocStatus,
    'village' : IDL.Text,
    'block' : IDL.Text,
    'farmerName' : IDL.Text,
  });
  const SaleFields = IDL.Record({
    'productCategoryId' : IDL.Nat,
    'productId' : IDL.Nat,
    'priority' : Priority,
    'place' : IDL.Opt(IDL.Text),
    'followUpDate' : IDL.Opt(Timestamp),
  });
  const AgriDetails = IDL.Record({
    'subType' : AgriSubType,
    'subsidyFields' : IDL.Opt(SubsidyFields),
    'saleFields' : IDL.Opt(SaleFields),
  });
  const CallDetails = IDL.Variant({
    'Agri' : AgriDetails,
    'CivilEquip' : SaleFields,
    'IndustrialEquip' : SaleFields,
  });
  const CallOutcome = IDL.Variant({
    'NotReachable' : IDL.Null,
    'SwitchOff' : IDL.Null,
    'Interested' : IDL.Null,
    'NotInterested' : IDL.Null,
  });
  const CallLog = IDL.Record({
    'id' : IDL.Nat,
    'duration' : IDL.Opt(IDL.Nat),
    'callStatus' : CallStatus,
    'createdAt' : Timestamp,
    'callerId' : UserId,
    'leadId' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
    'callTimestamp' : Timestamp,
    'details' : IDL.Opt(CallDetails),
    'outcome' : IDL.Opt(CallOutcome),
  });
  const FollowUp = IDL.Record({
    'id' : IDL.Nat,
    'isCompleted' : IDL.Bool,
    'scheduledDate' : IDL.Text,
    'scheduledTime' : IDL.Text,
    'createdAt' : Timestamp,
    'reminderEnabled' : IDL.Bool,
    'leadId' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
    'completionNotes' : IDL.Opt(IDL.Text),
  });
  const LeadReportFilter = IDL.Record({
    'source' : IDL.Opt(IDL.Text),
    'campaign' : IDL.Opt(IDL.Text),
    'userId' : IDL.Opt(UserId),
    'dateRange' : IDL.Opt(DateRange),
  });
  const LeadReport = IDL.Record({
    'closedWon' : IDL.Nat,
    'totalLeads' : IDL.Nat,
    'proposalSent' : IDL.Nat,
    'newLeads' : IDL.Nat,
    'conversionPercent' : IDL.Nat,
    'qualified' : IDL.Nat,
    'closedLost' : IDL.Nat,
  });
  const LeadFilter = IDL.Record({
    'status' : IDL.Opt(LeadStatus),
    'source' : IDL.Opt(IDL.Text),
    'campaign' : IDL.Opt(IDL.Text),
    'searchText' : IDL.Opt(IDL.Text),
    'priority' : IDL.Opt(Priority),
    'assignedUserId' : IDL.Opt(UserId),
  });
  const LogCallInput = IDL.Record({
    'duration' : IDL.Opt(IDL.Nat),
    'callStatus' : CallStatus,
    'leadId' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
    'callTimestamp' : Timestamp,
    'details' : IDL.Opt(CallDetails),
    'outcome' : IDL.Opt(CallOutcome),
  });
  const CreateFollowUpInput = IDL.Record({
    'scheduledDate' : IDL.Text,
    'scheduledTime' : IDL.Text,
    'reminderEnabled' : IDL.Bool,
    'leadId' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
  });
  const FollowUpFilter = IDL.Variant({
    'Missed' : IDL.Null,
    'Today' : IDL.Null,
    'Completed' : IDL.Null,
    'Upcoming' : IDL.Null,
  });
  const UpdateFollowUpInput = IDL.Record({
    'id' : IDL.Nat,
    'isCompleted' : IDL.Opt(IDL.Bool),
    'scheduledDate' : IDL.Opt(IDL.Text),
    'scheduledTime' : IDL.Opt(IDL.Text),
    'reminderEnabled' : IDL.Opt(IDL.Bool),
    'notes' : IDL.Opt(IDL.Text),
    'completionNotes' : IDL.Opt(IDL.Text),
  });
  const UpdateLeadInput = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Opt(LeadStatus),
    'source' : IDL.Opt(IDL.Text),
    'campaign' : IDL.Opt(IDL.Text),
    'name' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
    'notes' : IDL.Opt(IDL.Text),
    'productInterest' : IDL.Opt(IDL.Text),
    'priority' : IDL.Opt(Priority),
    'phone' : IDL.Opt(IDL.Text),
    'assignedUserId' : IDL.Opt(UserId),
    'altPhone' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addBranch' : IDL.Func([IDL.Text], [Branch], []),
    'addCampaign' : IDL.Func([Campaign], [Campaign], []),
    'addLead' : IDL.Func([CreateLeadInput], [Lead], []),
    'addProduct' : IDL.Func([IDL.Nat, IDL.Text], [Product], []),
    'addProductCategory' : IDL.Func([IDL.Text], [ProductCategory], []),
    'addSource' : IDL.Func([IDL.Text], [Source], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignLead' : IDL.Func([IDL.Nat, UserId], [IDL.Bool], []),
    'assignUserRole' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'deleteBranch' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteCampaign' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteFollowUp' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteLead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteProductCategory' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteSource' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getCallReport' : IDL.Func([CallReportFilter], [CallReport], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserInfo)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCallsForLead' : IDL.Func([IDL.Nat], [IDL.Vec(CallLog)], ['query']),
    'getFollowUpsForLead' : IDL.Func([IDL.Nat], [IDL.Vec(FollowUp)], ['query']),
    'getLeadById' : IDL.Func([IDL.Nat], [IDL.Opt(Lead)], ['query']),
    'getLeadReport' : IDL.Func([LeadReportFilter], [LeadReport], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserInfo)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listBranches' : IDL.Func([], [IDL.Vec(Branch)], ['query']),
    'listCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
    'listLeads' : IDL.Func([IDL.Opt(LeadFilter)], [IDL.Vec(Lead)], ['query']),
    'listProductCategories' : IDL.Func(
        [],
        [IDL.Vec(ProductCategory)],
        ['query'],
      ),
    'listProducts' : IDL.Func(
        [IDL.Opt(IDL.Nat)],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'listSources' : IDL.Func([], [IDL.Vec(Source)], ['query']),
    'listUsers' : IDL.Func([], [IDL.Vec(UserInfo)], ['query']),
    'logCall' : IDL.Func([LogCallInput], [CallLog], []),
    'logFollowUp' : IDL.Func([CreateFollowUpInput], [FollowUp], []),
    'queryFollowUps' : IDL.Func(
        [FollowUpFilter],
        [IDL.Vec(FollowUp)],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([IDL.Text], [], []),
    'updateBranch' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'updateCampaign' : IDL.Func([Campaign], [IDL.Bool], []),
    'updateFollowUpStatus' : IDL.Func([UpdateFollowUpInput], [IDL.Bool], []),
    'updateLead' : IDL.Func([UpdateLeadInput], [IDL.Bool], []),
    'updateProduct' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'updateProductCategory' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'updateSource' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };