/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface LogCallInput {
    duration?: bigint;
    callStatus: CallStatus;
    leadId: bigint;
    notes?: string;
    callTimestamp: Timestamp;
    details?: CallDetails;
    outcome?: CallOutcome;
}
export interface CreateLeadInput {
    status: LeadStatus;
    source?: string;
    campaign?: string;
    name: string;
    email?: string;
    notes?: string;
    productInterest?: string;
    priority: Priority;
    phone: string;
    assignedUserId?: UserId;
    altPhone?: string;
}
export interface AgriDetails {
    subType: AgriSubType;
    subsidyFields?: SubsidyFields;
    saleFields?: SaleFields;
}
export interface LeadFilter {
    status?: LeadStatus;
    source?: string;
    campaign?: string;
    searchText?: string;
    priority?: Priority;
    assignedUserId?: UserId;
}
export interface UserInfo {
    id: Principal;
    name: string;
    role: string;
}
export interface Lead {
    id: bigint;
    status: LeadStatus;
    source?: string;
    campaign?: string;
    name: string;
    createdAt: Timestamp;
    email?: string;
    updatedAt: Timestamp;
    notes?: string;
    productInterest?: string;
    priority: Priority;
    phone: string;
    assignedUserId?: UserId;
    altPhone?: string;
}
export interface LeadReportFilter {
    source?: string;
    campaign?: string;
    userId?: UserId;
    dateRange?: DateRange;
}
export interface Campaign {
    id: bigint;
    endDate?: string;
    source?: string;
    name: string;
    isActive: boolean;
    budget?: bigint;
    startDate?: string;
}
export interface SaleFields {
    productCategoryId: bigint;
    productId: bigint;
    priority: Priority;
    place?: string;
    followUpDate?: Timestamp;
}
export interface Source {
    id: bigint;
    name: string;
    isActive: boolean;
}
export interface LeadReport {
    closedWon: bigint;
    totalLeads: bigint;
    proposalSent: bigint;
    newLeads: bigint;
    conversionPercent: bigint;
    qualified: bigint;
    closedLost: bigint;
}
export interface ProductCategory {
    id: bigint;
    name: string;
    isActive: boolean;
}
export type CallDetails = {
    __kind__: "Agri";
    Agri: AgriDetails;
} | {
    __kind__: "CivilEquip";
    CivilEquip: SaleFields;
} | {
    __kind__: "IndustrialEquip";
    IndustrialEquip: SaleFields;
};
export interface CallLog {
    id: bigint;
    duration?: bigint;
    callStatus: CallStatus;
    createdAt: Timestamp;
    callerId: UserId;
    leadId: bigint;
    notes?: string;
    callTimestamp: Timestamp;
    details?: CallDetails;
    outcome?: CallOutcome;
}
export interface CallReportFilter {
    userId?: UserId;
    dateRange?: DateRange;
}
export interface CallReport {
    switchOffCount: bigint;
    totalDurationSecs: bigint;
    totalCalls: bigint;
    interestedCount: bigint;
    notReachableCount: bigint;
    notConnectedCalls: bigint;
    connectedCalls: bigint;
    notInterestedCount: bigint;
}
export type UserId = Principal;
export interface DateRange {
    toTs: Timestamp;
    fromTs: Timestamp;
}
export interface UpdateFollowUpInput {
    id: bigint;
    isCompleted?: boolean;
    scheduledDate?: string;
    scheduledTime?: string;
    reminderEnabled?: boolean;
    notes?: string;
    completionNotes?: string;
}
export interface CreateFollowUpInput {
    scheduledDate: string;
    scheduledTime: string;
    reminderEnabled: boolean;
    leadId: bigint;
    notes?: string;
}
export interface SubsidyFields {
    productCategoryId: bigint;
    division?: string;
    productId: bigint;
    district: string;
    docStatus: DocStatus;
    village: string;
    block: string;
    farmerName: string;
}
export interface FollowUp {
    id: bigint;
    isCompleted: boolean;
    scheduledDate: string;
    scheduledTime: string;
    createdAt: Timestamp;
    reminderEnabled: boolean;
    leadId: bigint;
    notes?: string;
    completionNotes?: string;
}
export interface UpdateLeadInput {
    id: bigint;
    status?: LeadStatus;
    source?: string;
    campaign?: string;
    name?: string;
    email?: string;
    notes?: string;
    productInterest?: string;
    priority?: Priority;
    phone?: string;
    assignedUserId?: UserId;
    altPhone?: string;
}
export interface Branch {
    id: bigint;
    name: string;
    isActive: boolean;
}
export interface Product {
    id: bigint;
    categoryId: bigint;
    name: string;
    isActive: boolean;
}
export enum AgriSubType {
    Sale = "Sale",
    Subsidy = "Subsidy"
}
export enum CallOutcome {
    NotReachable = "NotReachable",
    SwitchOff = "SwitchOff",
    Interested = "Interested",
    NotInterested = "NotInterested"
}
export enum CallStatus {
    Connected = "Connected",
    NotConnected = "NotConnected"
}
export enum DocStatus {
    Collected = "Collected",
    Pending = "Pending"
}
export enum FollowUpFilter {
    Missed = "Missed",
    Today = "Today",
    Completed = "Completed",
    Upcoming = "Upcoming"
}
export enum LeadStatus {
    New = "New",
    Proposal = "Proposal",
    ClosedWon = "ClosedWon",
    Interested = "Interested",
    ClosedLost = "ClosedLost"
}
export enum Priority {
    Hot = "Hot",
    Cold = "Cold",
    Warm = "Warm"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addBranch(name: string): Promise<Branch>;
    addCampaign(input: Campaign): Promise<Campaign>;
    addLead(input: CreateLeadInput): Promise<Lead>;
    addProduct(categoryId: bigint, name: string): Promise<Product>;
    addProductCategory(name: string): Promise<ProductCategory>;
    addSource(name: string): Promise<Source>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignLead(id: bigint, userId: UserId): Promise<boolean>;
    assignUserRole(user: Principal, role: string): Promise<void>;
    deleteBranch(id: bigint): Promise<boolean>;
    deleteCampaign(id: bigint): Promise<boolean>;
    deleteFollowUp(id: bigint): Promise<boolean>;
    deleteLead(id: bigint): Promise<boolean>;
    deleteProduct(id: bigint): Promise<boolean>;
    deleteProductCategory(id: bigint): Promise<boolean>;
    deleteSource(id: bigint): Promise<boolean>;
    getCallReport(filter: CallReportFilter): Promise<CallReport>;
    getCallerUserProfile(): Promise<UserInfo | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCallsForLead(leadId: bigint): Promise<Array<CallLog>>;
    getFollowUpsForLead(leadId: bigint): Promise<Array<FollowUp>>;
    getLeadById(id: bigint): Promise<Lead | null>;
    getLeadReport(filter: LeadReportFilter): Promise<LeadReport>;
    getUserProfile(user: Principal): Promise<UserInfo | null>;
    isCallerAdmin(): Promise<boolean>;
    listBranches(): Promise<Array<Branch>>;
    listCampaigns(): Promise<Array<Campaign>>;
    listLeads(filter: LeadFilter | null): Promise<Array<Lead>>;
    listProductCategories(): Promise<Array<ProductCategory>>;
    listProducts(categoryId: bigint | null): Promise<Array<Product>>;
    listSources(): Promise<Array<Source>>;
    listUsers(): Promise<Array<UserInfo>>;
    logCall(input: LogCallInput): Promise<CallLog>;
    logFollowUp(input: CreateFollowUpInput): Promise<FollowUp>;
    queryFollowUps(filterType: FollowUpFilter): Promise<Array<FollowUp>>;
    saveCallerUserProfile(name: string): Promise<void>;
    updateBranch(id: bigint, name: string): Promise<boolean>;
    updateCampaign(input: Campaign): Promise<boolean>;
    updateFollowUpStatus(input: UpdateFollowUpInput): Promise<boolean>;
    updateLead(input: UpdateLeadInput): Promise<boolean>;
    updateProduct(id: bigint, name: string): Promise<boolean>;
    updateProductCategory(id: bigint, name: string): Promise<boolean>;
    updateSource(id: bigint, name: string): Promise<boolean>;
}
import type { AgriDetails as _AgriDetails, AgriSubType as _AgriSubType, CallDetails as _CallDetails, CallLog as _CallLog, CallOutcome as _CallOutcome, CallReportFilter as _CallReportFilter, CallStatus as _CallStatus, Campaign as _Campaign, CreateFollowUpInput as _CreateFollowUpInput, CreateLeadInput as _CreateLeadInput, DateRange as _DateRange, DocStatus as _DocStatus, FollowUp as _FollowUp, FollowUpFilter as _FollowUpFilter, Lead as _Lead, LeadFilter as _LeadFilter, LeadReportFilter as _LeadReportFilter, LeadStatus as _LeadStatus, LogCallInput as _LogCallInput, Priority as _Priority, SaleFields as _SaleFields, SubsidyFields as _SubsidyFields, Timestamp as _Timestamp, UpdateFollowUpInput as _UpdateFollowUpInput, UpdateLeadInput as _UpdateLeadInput, UserId as _UserId, UserInfo as _UserInfo, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addBranch(arg0: string): Promise<Branch> {
        if (this.processError) {
            try {
                const result = await this.actor.addBranch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBranch(arg0);
            return result;
        }
    }
    async addCampaign(arg0: Campaign): Promise<Campaign> {
        if (this.processError) {
            try {
                const result = await this.actor.addCampaign(to_candid_Campaign_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Campaign_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCampaign(to_candid_Campaign_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Campaign_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async addLead(arg0: CreateLeadInput): Promise<Lead> {
        if (this.processError) {
            try {
                const result = await this.actor.addLead(to_candid_CreateLeadInput_n7(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Lead_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLead(to_candid_CreateLeadInput_n7(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Lead_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async addProduct(arg0: bigint, arg1: string): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0, arg1);
            return result;
        }
    }
    async addProductCategory(arg0: string): Promise<ProductCategory> {
        if (this.processError) {
            try {
                const result = await this.actor.addProductCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProductCategory(arg0);
            return result;
        }
    }
    async addSource(arg0: string): Promise<Source> {
        if (this.processError) {
            try {
                const result = await this.actor.addSource(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSource(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n20(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n20(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignLead(arg0: bigint, arg1: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.assignLead(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignLead(arg0, arg1);
            return result;
        }
    }
    async assignUserRole(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignUserRole(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignUserRole(arg0, arg1);
            return result;
        }
    }
    async deleteBranch(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBranch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBranch(arg0);
            return result;
        }
    }
    async deleteCampaign(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCampaign(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCampaign(arg0);
            return result;
        }
    }
    async deleteFollowUp(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFollowUp(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFollowUp(arg0);
            return result;
        }
    }
    async deleteLead(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLead(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async deleteProductCategory(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProductCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProductCategory(arg0);
            return result;
        }
    }
    async deleteSource(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSource(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSource(arg0);
            return result;
        }
    }
    async getCallReport(arg0: CallReportFilter): Promise<CallReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallReport(to_candid_CallReportFilter_n22(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallReport(to_candid_CallReportFilter_n22(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallsForLead(arg0: bigint): Promise<Array<CallLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallsForLead(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallsForLead(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowUpsForLead(arg0: bigint): Promise<Array<FollowUp>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowUpsForLead(arg0);
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowUpsForLead(arg0);
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeadById(arg0: bigint): Promise<Lead | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadById(arg0);
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadById(arg0);
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeadReport(arg0: LeadReportFilter): Promise<LeadReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadReport(to_candid_LeadReportFilter_n55(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadReport(to_candid_LeadReportFilter_n55(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listBranches(): Promise<Array<Branch>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBranches();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBranches();
            return result;
        }
    }
    async listCampaigns(): Promise<Array<Campaign>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCampaigns();
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCampaigns();
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async listLeads(arg0: LeadFilter | null): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLeads(to_candid_opt_n58(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLeads(to_candid_opt_n58(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProductCategories(): Promise<Array<ProductCategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProductCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProductCategories();
            return result;
        }
    }
    async listProducts(arg0: bigint | null): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProducts(to_candid_opt_n62(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProducts(to_candid_opt_n62(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async listSources(): Promise<Array<Source>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSources();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSources();
            return result;
        }
    }
    async listUsers(): Promise<Array<UserInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return result;
        }
    }
    async logCall(arg0: LogCallInput): Promise<CallLog> {
        if (this.processError) {
            try {
                const result = await this.actor.logCall(to_candid_LogCallInput_n63(this._uploadFile, this._downloadFile, arg0));
                return from_candid_CallLog_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logCall(to_candid_LogCallInput_n63(this._uploadFile, this._downloadFile, arg0));
            return from_candid_CallLog_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async logFollowUp(arg0: CreateFollowUpInput): Promise<FollowUp> {
        if (this.processError) {
            try {
                const result = await this.actor.logFollowUp(to_candid_CreateFollowUpInput_n81(this._uploadFile, this._downloadFile, arg0));
                return from_candid_FollowUp_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logFollowUp(to_candid_CreateFollowUpInput_n81(this._uploadFile, this._downloadFile, arg0));
            return from_candid_FollowUp_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async queryFollowUps(arg0: FollowUpFilter): Promise<Array<FollowUp>> {
        if (this.processError) {
            try {
                const result = await this.actor.queryFollowUps(to_candid_FollowUpFilter_n83(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.queryFollowUps(to_candid_FollowUpFilter_n83(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateBranch(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBranch(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBranch(arg0, arg1);
            return result;
        }
    }
    async updateCampaign(arg0: Campaign): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCampaign(to_candid_Campaign_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCampaign(to_candid_Campaign_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateFollowUpStatus(arg0: UpdateFollowUpInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFollowUpStatus(to_candid_UpdateFollowUpInput_n85(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFollowUpStatus(to_candid_UpdateFollowUpInput_n85(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateLead(arg0: UpdateLeadInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLead(to_candid_UpdateLeadInput_n87(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLead(to_candid_UpdateLeadInput_n87(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateProduct(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1);
            return result;
        }
    }
    async updateProductCategory(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProductCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProductCategory(arg0, arg1);
            return result;
        }
    }
    async updateSource(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSource(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSource(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AgriDetails_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AgriDetails): AgriDetails {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_AgriSubType_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AgriSubType): AgriSubType {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_CallDetails_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CallDetails): CallDetails {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_CallLog_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CallLog): CallLog {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_CallOutcome_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CallOutcome): CallOutcome {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_CallStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CallStatus): CallStatus {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Campaign_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Campaign): Campaign {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_DocStatus_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocStatus): DocStatus {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_FollowUp_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FollowUp): FollowUp {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_LeadStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeadStatus): LeadStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Lead_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lead): Lead {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Priority_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Priority): Priority {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_SaleFields_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SaleFields): SaleFields {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_SubsidyFields_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubsidyFields): SubsidyFields {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserInfo]): UserInfo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CallDetails]): CallDetails | null {
    return value.length === 0 ? null : from_candid_CallDetails_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SubsidyFields]): SubsidyFields | null {
    return value.length === 0 ? null : from_candid_SubsidyFields_n40(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SaleFields]): SaleFields | null {
    return value.length === 0 ? null : from_candid_SaleFields_n45(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CallOutcome]): CallOutcome | null {
    return value.length === 0 ? null : from_candid_CallOutcome_n49(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Lead]): Lead | null {
    return value.length === 0 ? null : from_candid_Lead_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _LeadStatus;
    source: [] | [string];
    campaign: [] | [string];
    name: string;
    createdAt: _Timestamp;
    email: [] | [string];
    updatedAt: _Timestamp;
    notes: [] | [string];
    productInterest: [] | [string];
    priority: _Priority;
    phone: string;
    assignedUserId: [] | [_UserId];
    altPhone: [] | [string];
}): {
    id: bigint;
    status: LeadStatus;
    source?: string;
    campaign?: string;
    name: string;
    createdAt: Timestamp;
    email?: string;
    updatedAt: Timestamp;
    notes?: string;
    productInterest?: string;
    priority: Priority;
    phone: string;
    assignedUserId?: UserId;
    altPhone?: string;
} {
    return {
        id: value.id,
        status: from_candid_LeadStatus_n15(_uploadFile, _downloadFile, value.status),
        source: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.source)),
        campaign: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.campaign)),
        name: value.name,
        createdAt: value.createdAt,
        email: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.email)),
        updatedAt: value.updatedAt,
        notes: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.notes)),
        productInterest: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.productInterest)),
        priority: from_candid_Priority_n17(_uploadFile, _downloadFile, value.priority),
        phone: value.phone,
        assignedUserId: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.assignedUserId)),
        altPhone: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.altPhone))
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    duration: [] | [bigint];
    callStatus: _CallStatus;
    createdAt: _Timestamp;
    callerId: _UserId;
    leadId: bigint;
    notes: [] | [string];
    callTimestamp: _Timestamp;
    details: [] | [_CallDetails];
    outcome: [] | [_CallOutcome];
}): {
    id: bigint;
    duration?: bigint;
    callStatus: CallStatus;
    createdAt: Timestamp;
    callerId: UserId;
    leadId: bigint;
    notes?: string;
    callTimestamp: Timestamp;
    details?: CallDetails;
    outcome?: CallOutcome;
} {
    return {
        id: value.id,
        duration: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.duration)),
        callStatus: from_candid_CallStatus_n30(_uploadFile, _downloadFile, value.callStatus),
        createdAt: value.createdAt,
        callerId: value.callerId,
        leadId: value.leadId,
        notes: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.notes)),
        callTimestamp: value.callTimestamp,
        details: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.details)),
        outcome: record_opt_to_undefined(from_candid_opt_n48(_uploadFile, _downloadFile, value.outcome))
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subType: _AgriSubType;
    subsidyFields: [] | [_SubsidyFields];
    saleFields: [] | [_SaleFields];
}): {
    subType: AgriSubType;
    subsidyFields?: SubsidyFields;
    saleFields?: SaleFields;
} {
    return {
        subType: from_candid_AgriSubType_n37(_uploadFile, _downloadFile, value.subType),
        subsidyFields: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.subsidyFields)),
        saleFields: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.saleFields))
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    endDate: [] | [string];
    source: [] | [string];
    name: string;
    isActive: boolean;
    budget: [] | [bigint];
    startDate: [] | [string];
}): {
    id: bigint;
    endDate?: string;
    source?: string;
    name: string;
    isActive: boolean;
    budget?: bigint;
    startDate?: string;
} {
    return {
        id: value.id,
        endDate: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.endDate)),
        source: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.source)),
        name: value.name,
        isActive: value.isActive,
        budget: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.budget)),
        startDate: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.startDate))
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    productCategoryId: bigint;
    division: [] | [string];
    productId: bigint;
    district: string;
    docStatus: _DocStatus;
    village: string;
    block: string;
    farmerName: string;
}): {
    productCategoryId: bigint;
    division?: string;
    productId: bigint;
    district: string;
    docStatus: DocStatus;
    village: string;
    block: string;
    farmerName: string;
} {
    return {
        productCategoryId: value.productCategoryId,
        division: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.division)),
        productId: value.productId,
        district: value.district,
        docStatus: from_candid_DocStatus_n42(_uploadFile, _downloadFile, value.docStatus),
        village: value.village,
        block: value.block,
        farmerName: value.farmerName
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    productCategoryId: bigint;
    productId: bigint;
    priority: _Priority;
    place: [] | [string];
    followUpDate: [] | [_Timestamp];
}): {
    productCategoryId: bigint;
    productId: bigint;
    priority: Priority;
    place?: string;
    followUpDate?: Timestamp;
} {
    return {
        productCategoryId: value.productCategoryId,
        productId: value.productId,
        priority: from_candid_Priority_n17(_uploadFile, _downloadFile, value.priority),
        place: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.place)),
        followUpDate: record_opt_to_undefined(from_candid_opt_n47(_uploadFile, _downloadFile, value.followUpDate))
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    isCompleted: boolean;
    scheduledDate: string;
    scheduledTime: string;
    createdAt: _Timestamp;
    reminderEnabled: boolean;
    leadId: bigint;
    notes: [] | [string];
    completionNotes: [] | [string];
}): {
    id: bigint;
    isCompleted: boolean;
    scheduledDate: string;
    scheduledTime: string;
    createdAt: Timestamp;
    reminderEnabled: boolean;
    leadId: bigint;
    notes?: string;
    completionNotes?: string;
} {
    return {
        id: value.id,
        isCompleted: value.isCompleted,
        scheduledDate: value.scheduledDate,
        scheduledTime: value.scheduledTime,
        createdAt: value.createdAt,
        reminderEnabled: value.reminderEnabled,
        leadId: value.leadId,
        notes: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.notes)),
        completionNotes: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.completionNotes))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    New: null;
} | {
    Proposal: null;
} | {
    ClosedWon: null;
} | {
    Interested: null;
} | {
    ClosedLost: null;
}): LeadStatus {
    return "New" in value ? LeadStatus.New : "Proposal" in value ? LeadStatus.Proposal : "ClosedWon" in value ? LeadStatus.ClosedWon : "Interested" in value ? LeadStatus.Interested : "ClosedLost" in value ? LeadStatus.ClosedLost : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Hot: null;
} | {
    Cold: null;
} | {
    Warm: null;
}): Priority {
    return "Hot" in value ? Priority.Hot : "Cold" in value ? Priority.Cold : "Warm" in value ? Priority.Warm : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Connected: null;
} | {
    NotConnected: null;
}): CallStatus {
    return "Connected" in value ? CallStatus.Connected : "NotConnected" in value ? CallStatus.NotConnected : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Agri: _AgriDetails;
} | {
    CivilEquip: _SaleFields;
} | {
    IndustrialEquip: _SaleFields;
}): {
    __kind__: "Agri";
    Agri: AgriDetails;
} | {
    __kind__: "CivilEquip";
    CivilEquip: SaleFields;
} | {
    __kind__: "IndustrialEquip";
    IndustrialEquip: SaleFields;
} {
    return "Agri" in value ? {
        __kind__: "Agri",
        Agri: from_candid_AgriDetails_n35(_uploadFile, _downloadFile, value.Agri)
    } : "CivilEquip" in value ? {
        __kind__: "CivilEquip",
        CivilEquip: from_candid_SaleFields_n45(_uploadFile, _downloadFile, value.CivilEquip)
    } : "IndustrialEquip" in value ? {
        __kind__: "IndustrialEquip",
        IndustrialEquip: from_candid_SaleFields_n45(_uploadFile, _downloadFile, value.IndustrialEquip)
    } : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Sale: null;
} | {
    Subsidy: null;
}): AgriSubType {
    return "Sale" in value ? AgriSubType.Sale : "Subsidy" in value ? AgriSubType.Subsidy : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Collected: null;
} | {
    Pending: null;
}): DocStatus {
    return "Collected" in value ? DocStatus.Collected : "Pending" in value ? DocStatus.Pending : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    NotReachable: null;
} | {
    SwitchOff: null;
} | {
    Interested: null;
} | {
    NotInterested: null;
}): CallOutcome {
    return "NotReachable" in value ? CallOutcome.NotReachable : "SwitchOff" in value ? CallOutcome.SwitchOff : "Interested" in value ? CallOutcome.Interested : "NotInterested" in value ? CallOutcome.NotInterested : value;
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CallLog>): Array<CallLog> {
    return value.map((x)=>from_candid_CallLog_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FollowUp>): Array<FollowUp> {
    return value.map((x)=>from_candid_FollowUp_n52(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Campaign>): Array<Campaign> {
    return value.map((x)=>from_candid_Campaign_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Lead>): Array<Lead> {
    return value.map((x)=>from_candid_Lead_n13(_uploadFile, _downloadFile, x));
}
function to_candid_AgriDetails_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AgriDetails): _AgriDetails {
    return to_candid_record_n72(_uploadFile, _downloadFile, value);
}
function to_candid_AgriSubType_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AgriSubType): _AgriSubType {
    return to_candid_variant_n74(_uploadFile, _downloadFile, value);
}
function to_candid_CallDetails_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CallDetails): _CallDetails {
    return to_candid_variant_n68(_uploadFile, _downloadFile, value);
}
function to_candid_CallOutcome_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CallOutcome): _CallOutcome {
    return to_candid_variant_n80(_uploadFile, _downloadFile, value);
}
function to_candid_CallReportFilter_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CallReportFilter): _CallReportFilter {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_CallStatus_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CallStatus): _CallStatus {
    return to_candid_variant_n66(_uploadFile, _downloadFile, value);
}
function to_candid_Campaign_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Campaign): _Campaign {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_CreateFollowUpInput_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateFollowUpInput): _CreateFollowUpInput {
    return to_candid_record_n82(_uploadFile, _downloadFile, value);
}
function to_candid_CreateLeadInput_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateLeadInput): _CreateLeadInput {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_DocStatus_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocStatus): _DocStatus {
    return to_candid_variant_n78(_uploadFile, _downloadFile, value);
}
function to_candid_FollowUpFilter_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FollowUpFilter): _FollowUpFilter {
    return to_candid_variant_n84(_uploadFile, _downloadFile, value);
}
function to_candid_LeadFilter_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadFilter): _LeadFilter {
    return to_candid_record_n60(_uploadFile, _downloadFile, value);
}
function to_candid_LeadReportFilter_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadReportFilter): _LeadReportFilter {
    return to_candid_record_n56(_uploadFile, _downloadFile, value);
}
function to_candid_LeadStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadStatus): _LeadStatus {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_LogCallInput_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LogCallInput): _LogCallInput {
    return to_candid_record_n64(_uploadFile, _downloadFile, value);
}
function to_candid_Priority_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): _Priority {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_SaleFields_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SaleFields): _SaleFields {
    return to_candid_record_n70(_uploadFile, _downloadFile, value);
}
function to_candid_SubsidyFields_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubsidyFields): _SubsidyFields {
    return to_candid_record_n76(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateFollowUpInput_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateFollowUpInput): _UpdateFollowUpInput {
    return to_candid_record_n86(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateLeadInput_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateLeadInput): _UpdateLeadInput {
    return to_candid_record_n88(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadFilter | null): [] | [_LeadFilter] {
    return value === null ? candid_none() : candid_some(to_candid_LeadFilter_n59(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    endDate?: string;
    source?: string;
    name: string;
    isActive: boolean;
    budget?: bigint;
    startDate?: string;
}): {
    id: bigint;
    endDate: [] | [string];
    source: [] | [string];
    name: string;
    isActive: boolean;
    budget: [] | [bigint];
    startDate: [] | [string];
} {
    return {
        id: value.id,
        endDate: value.endDate ? candid_some(value.endDate) : candid_none(),
        source: value.source ? candid_some(value.source) : candid_none(),
        name: value.name,
        isActive: value.isActive,
        budget: value.budget ? candid_some(value.budget) : candid_none(),
        startDate: value.startDate ? candid_some(value.startDate) : candid_none()
    };
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId?: UserId;
    dateRange?: DateRange;
}): {
    userId: [] | [_UserId];
    dateRange: [] | [_DateRange];
} {
    return {
        userId: value.userId ? candid_some(value.userId) : candid_none(),
        dateRange: value.dateRange ? candid_some(value.dateRange) : candid_none()
    };
}
function to_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    source?: string;
    campaign?: string;
    userId?: UserId;
    dateRange?: DateRange;
}): {
    source: [] | [string];
    campaign: [] | [string];
    userId: [] | [_UserId];
    dateRange: [] | [_DateRange];
} {
    return {
        source: value.source ? candid_some(value.source) : candid_none(),
        campaign: value.campaign ? candid_some(value.campaign) : candid_none(),
        userId: value.userId ? candid_some(value.userId) : candid_none(),
        dateRange: value.dateRange ? candid_some(value.dateRange) : candid_none()
    };
}
function to_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: LeadStatus;
    source?: string;
    campaign?: string;
    searchText?: string;
    priority?: Priority;
    assignedUserId?: UserId;
}): {
    status: [] | [_LeadStatus];
    source: [] | [string];
    campaign: [] | [string];
    searchText: [] | [string];
    priority: [] | [_Priority];
    assignedUserId: [] | [_UserId];
} {
    return {
        status: value.status ? candid_some(to_candid_LeadStatus_n9(_uploadFile, _downloadFile, value.status)) : candid_none(),
        source: value.source ? candid_some(value.source) : candid_none(),
        campaign: value.campaign ? candid_some(value.campaign) : candid_none(),
        searchText: value.searchText ? candid_some(value.searchText) : candid_none(),
        priority: value.priority ? candid_some(to_candid_Priority_n11(_uploadFile, _downloadFile, value.priority)) : candid_none(),
        assignedUserId: value.assignedUserId ? candid_some(value.assignedUserId) : candid_none()
    };
}
function to_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    duration?: bigint;
    callStatus: CallStatus;
    leadId: bigint;
    notes?: string;
    callTimestamp: Timestamp;
    details?: CallDetails;
    outcome?: CallOutcome;
}): {
    duration: [] | [bigint];
    callStatus: _CallStatus;
    leadId: bigint;
    notes: [] | [string];
    callTimestamp: _Timestamp;
    details: [] | [_CallDetails];
    outcome: [] | [_CallOutcome];
} {
    return {
        duration: value.duration ? candid_some(value.duration) : candid_none(),
        callStatus: to_candid_CallStatus_n65(_uploadFile, _downloadFile, value.callStatus),
        leadId: value.leadId,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        callTimestamp: value.callTimestamp,
        details: value.details ? candid_some(to_candid_CallDetails_n67(_uploadFile, _downloadFile, value.details)) : candid_none(),
        outcome: value.outcome ? candid_some(to_candid_CallOutcome_n79(_uploadFile, _downloadFile, value.outcome)) : candid_none()
    };
}
function to_candid_record_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    productCategoryId: bigint;
    productId: bigint;
    priority: Priority;
    place?: string;
    followUpDate?: Timestamp;
}): {
    productCategoryId: bigint;
    productId: bigint;
    priority: _Priority;
    place: [] | [string];
    followUpDate: [] | [_Timestamp];
} {
    return {
        productCategoryId: value.productCategoryId,
        productId: value.productId,
        priority: to_candid_Priority_n11(_uploadFile, _downloadFile, value.priority),
        place: value.place ? candid_some(value.place) : candid_none(),
        followUpDate: value.followUpDate ? candid_some(value.followUpDate) : candid_none()
    };
}
function to_candid_record_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subType: AgriSubType;
    subsidyFields?: SubsidyFields;
    saleFields?: SaleFields;
}): {
    subType: _AgriSubType;
    subsidyFields: [] | [_SubsidyFields];
    saleFields: [] | [_SaleFields];
} {
    return {
        subType: to_candid_AgriSubType_n73(_uploadFile, _downloadFile, value.subType),
        subsidyFields: value.subsidyFields ? candid_some(to_candid_SubsidyFields_n75(_uploadFile, _downloadFile, value.subsidyFields)) : candid_none(),
        saleFields: value.saleFields ? candid_some(to_candid_SaleFields_n69(_uploadFile, _downloadFile, value.saleFields)) : candid_none()
    };
}
function to_candid_record_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    productCategoryId: bigint;
    division?: string;
    productId: bigint;
    district: string;
    docStatus: DocStatus;
    village: string;
    block: string;
    farmerName: string;
}): {
    productCategoryId: bigint;
    division: [] | [string];
    productId: bigint;
    district: string;
    docStatus: _DocStatus;
    village: string;
    block: string;
    farmerName: string;
} {
    return {
        productCategoryId: value.productCategoryId,
        division: value.division ? candid_some(value.division) : candid_none(),
        productId: value.productId,
        district: value.district,
        docStatus: to_candid_DocStatus_n77(_uploadFile, _downloadFile, value.docStatus),
        village: value.village,
        block: value.block,
        farmerName: value.farmerName
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: LeadStatus;
    source?: string;
    campaign?: string;
    name: string;
    email?: string;
    notes?: string;
    productInterest?: string;
    priority: Priority;
    phone: string;
    assignedUserId?: UserId;
    altPhone?: string;
}): {
    status: _LeadStatus;
    source: [] | [string];
    campaign: [] | [string];
    name: string;
    email: [] | [string];
    notes: [] | [string];
    productInterest: [] | [string];
    priority: _Priority;
    phone: string;
    assignedUserId: [] | [_UserId];
    altPhone: [] | [string];
} {
    return {
        status: to_candid_LeadStatus_n9(_uploadFile, _downloadFile, value.status),
        source: value.source ? candid_some(value.source) : candid_none(),
        campaign: value.campaign ? candid_some(value.campaign) : candid_none(),
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none(),
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        productInterest: value.productInterest ? candid_some(value.productInterest) : candid_none(),
        priority: to_candid_Priority_n11(_uploadFile, _downloadFile, value.priority),
        phone: value.phone,
        assignedUserId: value.assignedUserId ? candid_some(value.assignedUserId) : candid_none(),
        altPhone: value.altPhone ? candid_some(value.altPhone) : candid_none()
    };
}
function to_candid_record_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduledDate: string;
    scheduledTime: string;
    reminderEnabled: boolean;
    leadId: bigint;
    notes?: string;
}): {
    scheduledDate: string;
    scheduledTime: string;
    reminderEnabled: boolean;
    leadId: bigint;
    notes: [] | [string];
} {
    return {
        scheduledDate: value.scheduledDate,
        scheduledTime: value.scheduledTime,
        reminderEnabled: value.reminderEnabled,
        leadId: value.leadId,
        notes: value.notes ? candid_some(value.notes) : candid_none()
    };
}
function to_candid_record_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    isCompleted?: boolean;
    scheduledDate?: string;
    scheduledTime?: string;
    reminderEnabled?: boolean;
    notes?: string;
    completionNotes?: string;
}): {
    id: bigint;
    isCompleted: [] | [boolean];
    scheduledDate: [] | [string];
    scheduledTime: [] | [string];
    reminderEnabled: [] | [boolean];
    notes: [] | [string];
    completionNotes: [] | [string];
} {
    return {
        id: value.id,
        isCompleted: value.isCompleted ? candid_some(value.isCompleted) : candid_none(),
        scheduledDate: value.scheduledDate ? candid_some(value.scheduledDate) : candid_none(),
        scheduledTime: value.scheduledTime ? candid_some(value.scheduledTime) : candid_none(),
        reminderEnabled: value.reminderEnabled ? candid_some(value.reminderEnabled) : candid_none(),
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        completionNotes: value.completionNotes ? candid_some(value.completionNotes) : candid_none()
    };
}
function to_candid_record_n88(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status?: LeadStatus;
    source?: string;
    campaign?: string;
    name?: string;
    email?: string;
    notes?: string;
    productInterest?: string;
    priority?: Priority;
    phone?: string;
    assignedUserId?: UserId;
    altPhone?: string;
}): {
    id: bigint;
    status: [] | [_LeadStatus];
    source: [] | [string];
    campaign: [] | [string];
    name: [] | [string];
    email: [] | [string];
    notes: [] | [string];
    productInterest: [] | [string];
    priority: [] | [_Priority];
    phone: [] | [string];
    assignedUserId: [] | [_UserId];
    altPhone: [] | [string];
} {
    return {
        id: value.id,
        status: value.status ? candid_some(to_candid_LeadStatus_n9(_uploadFile, _downloadFile, value.status)) : candid_none(),
        source: value.source ? candid_some(value.source) : candid_none(),
        campaign: value.campaign ? candid_some(value.campaign) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        email: value.email ? candid_some(value.email) : candid_none(),
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        productInterest: value.productInterest ? candid_some(value.productInterest) : candid_none(),
        priority: value.priority ? candid_some(to_candid_Priority_n11(_uploadFile, _downloadFile, value.priority)) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none(),
        assignedUserId: value.assignedUserId ? candid_some(value.assignedUserId) : candid_none(),
        altPhone: value.altPhone ? candid_some(value.altPhone) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadStatus): {
    New: null;
} | {
    Proposal: null;
} | {
    ClosedWon: null;
} | {
    Interested: null;
} | {
    ClosedLost: null;
} {
    return value == LeadStatus.New ? {
        New: null
    } : value == LeadStatus.Proposal ? {
        Proposal: null
    } : value == LeadStatus.ClosedWon ? {
        ClosedWon: null
    } : value == LeadStatus.Interested ? {
        Interested: null
    } : value == LeadStatus.ClosedLost ? {
        ClosedLost: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): {
    Hot: null;
} | {
    Cold: null;
} | {
    Warm: null;
} {
    return value == Priority.Hot ? {
        Hot: null
    } : value == Priority.Cold ? {
        Cold: null
    } : value == Priority.Warm ? {
        Warm: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CallStatus): {
    Connected: null;
} | {
    NotConnected: null;
} {
    return value == CallStatus.Connected ? {
        Connected: null
    } : value == CallStatus.NotConnected ? {
        NotConnected: null
    } : value;
}
function to_candid_variant_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "Agri";
    Agri: AgriDetails;
} | {
    __kind__: "CivilEquip";
    CivilEquip: SaleFields;
} | {
    __kind__: "IndustrialEquip";
    IndustrialEquip: SaleFields;
}): {
    Agri: _AgriDetails;
} | {
    CivilEquip: _SaleFields;
} | {
    IndustrialEquip: _SaleFields;
} {
    return value.__kind__ === "Agri" ? {
        Agri: to_candid_AgriDetails_n71(_uploadFile, _downloadFile, value.Agri)
    } : value.__kind__ === "CivilEquip" ? {
        CivilEquip: to_candid_SaleFields_n69(_uploadFile, _downloadFile, value.CivilEquip)
    } : value.__kind__ === "IndustrialEquip" ? {
        IndustrialEquip: to_candid_SaleFields_n69(_uploadFile, _downloadFile, value.IndustrialEquip)
    } : value;
}
function to_candid_variant_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AgriSubType): {
    Sale: null;
} | {
    Subsidy: null;
} {
    return value == AgriSubType.Sale ? {
        Sale: null
    } : value == AgriSubType.Subsidy ? {
        Subsidy: null
    } : value;
}
function to_candid_variant_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocStatus): {
    Collected: null;
} | {
    Pending: null;
} {
    return value == DocStatus.Collected ? {
        Collected: null
    } : value == DocStatus.Pending ? {
        Pending: null
    } : value;
}
function to_candid_variant_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CallOutcome): {
    NotReachable: null;
} | {
    SwitchOff: null;
} | {
    Interested: null;
} | {
    NotInterested: null;
} {
    return value == CallOutcome.NotReachable ? {
        NotReachable: null
    } : value == CallOutcome.SwitchOff ? {
        SwitchOff: null
    } : value == CallOutcome.Interested ? {
        Interested: null
    } : value == CallOutcome.NotInterested ? {
        NotInterested: null
    } : value;
}
function to_candid_variant_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FollowUpFilter): {
    Missed: null;
} | {
    Today: null;
} | {
    Completed: null;
} | {
    Upcoming: null;
} {
    return value == FollowUpFilter.Missed ? {
        Missed: null
    } : value == FollowUpFilter.Today ? {
        Today: null
    } : value == FollowUpFilter.Completed ? {
        Completed: null
    } : value == FollowUpFilter.Upcoming ? {
        Upcoming: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
